[package]
name = "xsun_desktop_pet"
version = "0.1.0"
description = "A Tauri App"
authors = ["xiaosun"]
edition = "2021"

[lib]
name = "xsun_desktop_pet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] } # 添加 tray-icon 功能
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
sysinfo = "0.30"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-clipboard-manager = "2.0"
md5 = "0.7"
urlencoding = "2.1.3"
base64 = "0.21"
git2 = { version = "0.18", features = ["vendored-openssl"] }
uuid = { version = "1.0", features = ["v4"] }
# AI相关依赖
tokio-util = { version = "0.7", features = ["codec"] }
cron = "0.12"
tokio-cron-scheduler = { version = "0.10" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_System_LibraryLoader",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",  # 鼠标钩子
    "Win32_UI_Input_KeyboardAndMouse"  # SendInput 模拟键盘
] }
